spring:
  application:
    name: management-server
#  mvc:
#    static-path-pattern: /**
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/managementdb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: DatahikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB

server:
  port: 8080
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: cn.baobao.server.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
file:
  image:
    path: E:/AppServerImgs/
    plog: E:/AppServerImgs/plogs/
    good: E:/AppServerImgs/goods/
    errinfo: E:/AppServerImgs/errinfos/
